service: spinot-backend
provider:
  name: aws
  runtime: python3.11
  stage: prod
  region: ${self:custom.region}
  iam:
    role:
      statements:
       - Effect: Allow
         Action:
           - "s3:GetObject"
           - "s3:PutObject"
           - "s3:DeleteObject"
         Resource:
           - "arn:aws:s3:::spinot-backend-bucket/*"
        # - Effect: Allow
        #   Action:
        #     - "dynamodb:PutItem"
        #     - "dynamodb:GetItem"
        #     - "dynamodb:UpdateItem"
        #     - "dynamodb:DeleteItem"
        #     - "dynamodb:Scan"
        #     - "dynamodb:BatchWriteItem"
        #   Resource:
        #     - "arn:aws:dynamodb:${self:custom.region}:971150201377:table/infty-user-table"
resources:
  Resources:
    SpinotBackendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: spinot-backend-bucket
# resources:
#   Resources:
#     Connection2Chat:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         TableName: onthefly-connection-table
#         AttributeDefinitions:
#           -
#             AttributeName: id
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: id
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 5
#           WriteCapacityUnits: 5
    # inBucketUS:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: images-us


plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  region: ${env:REGION, 'ap-northeast-2'}
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: true
    slim: false

package:
  exclude:
    - node_modules/**
    - venv/**
    - .git/**
    - .gitignore
    - .pre-commit-config.yaml
    - .vscode/**
    - .pytest_cache/**
    - .serverless/**
    - .serverlessrc
    - .serverlessignore
    - __pycache__/**

functions:
  app:
    handler: app.main.handler
    environment:
      REGION: ${self:custom.region}
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
      - http: 'GET /{proxy+}'
      - http: 'POST /{proxy+}'
      - http: 'PUT /{proxy+}'
      - http: 'DELETE /{proxy+}'
      - http: 'PATCH /{proxy+}'
      - http: 'OPTIONS /{proxy+}'
    timeout: 30
